idf_component_register(
    SRCS
        "src/main.cpp"
        "src/tinyml/model_inference.cpp"
        "src/tinyml/noise_bench_task.cpp"
    INCLUDE_DIRS
        "include"
        "include/model"
        "lib/tinyml_model"
    REQUIRES
        nvs_flash
        esp_timer
        esp_system
        espressif__esp-tflite-micro
)